name = "lean"
version = "0.1.0"
defaultTargets = ["Test"]

[[require]]
name = "Canonical"
git = "https://github.com/chasenorman/CanonicalLean"
rev = "v4.28.0"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"

[[lean_lib]]
name = "Test"